package net;

public enum CommandType {
	LOGIN, 
	CHECK_UPDATE, 
	CREATE_USER, DELETE_USER, UPDATE_USER, READ_USERS,
	FINISH, READ_PATIENTS, READ_CONSULTATIONS, UPDATE_CONSULTATION, CREATE_PATIENT, UPDATE_PATIENT, DELETE_PATIENT, DELETE_CONSULTATION, CREATE_CONSULTATION
}
