package view;

import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JPasswordField;

public class LoginDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 102L;

	/**
	 * Creates new form LoginDialog
	 */
	public LoginDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	public LoginDialog(){
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jusername = new javax.swing.JTextField();
		jpassword = new JPasswordField();
		jButtonOK = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Login");
		setResizable(false);

		jLabel1.setText("Username:");

		jLabel2.setText("Password:");

		jButtonOK.setText("Login");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(26)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jLabel2)
						.addComponent(jLabel1))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jButtonOK)
						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
							.addComponent(jusername)
							.addComponent(jpassword, GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
					.addContainerGap(27, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(58)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel1)
						.addComponent(jusername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(22)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel2)
						.addComponent(jpassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(31)
					.addComponent(jButtonOK)
					.addContainerGap(42, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public void openDialog() {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("System".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		this.setVisible(true);
	}

	public void closeDialog() {
		this.setVisible(false);
	}
	private javax.swing.JButton jButtonOK;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private JPasswordField jpassword;
	private javax.swing.JTextField jusername;

	// End of variables declaration//GEN-END:variables

	public String getUsername() {
		return jusername.getText();
	}

	@SuppressWarnings("deprecation")
	public String getPassword() {
		return jpassword.getText();
	}

	public void addOKListener(ActionListener a) {
		jButtonOK.addActionListener(a);
	}

	public void addWindowCloseListener(WindowListener a) {
		this.addWindowListener(a);
	}


}
